runtime = 10800.0
dt = 10.0
dt_output = 300.0

h = 100.0
beta = 0.2
div = 0.0

theta = 300.0
dtheta = 0.5
wtheta = 0.1
gammatheta = 0.003

q = 0.005
dq = -0.001
wq = 8e-5
gammaq = 0.0

dtheta_plume = 0.2
dq_plume = 0.001
